# Generated by Django 4.2.1 on 2023-06-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(default='', upload_to='imagens'),
            preserve_default=False,
        ),
    ]
